// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "MageForward":return img`
. . . . . . f f f f . . . . . . 
. . . . f f c c c c f f . . . . 
. . . f c c a a a a c c f . . . 
. . f c a a a a a a a a c f . . 
. f c a a a b b b b a a a c f . 
. f c a a b f f f f b a a c f . 
. f c a b f 1 f f 1 f b a c f . 
. f c a b f 5 f f 5 f b a c f . 
. f c a b f f f f f f b a c f . 
. . f c a b f f f f b a c f . . 
. . . f f c b b b b c f f . . . 
. . . f c a a 4 5 a a c f . . . 
. . f c a a a 5 2 a a a c f . . 
. f c a a a a c c a a a a c f . 
. f c a a a a c c a a a a c f . 
f c a a a a a c c a a a a a c f 
`;
            case "image2":
            case "MageBack":return img`
. . . . . . f f f f . . . . . . 
. . . . f f c c c c f f . . . . 
. . . f c c f a a f c c f . . . 
. . f c a a f a a f a a c f . . 
. f c a a a c f f c a a a c f . 
. f c a a a a c c a a a a c f . 
. f c a a a a a a a a a a c f . 
. f c a a a a a a a a a a c f . 
. f c c a a a a a a a a c c f . 
. . f c c a a a a a a c c f . . 
. . . f c c c a a c c c f . . . 
. . . f c c c c c c c c f . . . 
. . f c c a a a a a a c c f . . 
. f c c a a a a a a a a c c f . 
. f c a a a a a a a a a a c f . 
f c a a a a a a a a a a a a c f 
`;
            case "image3":
            case "MageRight":return img`
. . . f f f f f f f . . . . . . 
. . f c c c c c a a f f . . . . 
. . f c c c a a a a a a f . . . 
. f c c c a a a a a a a a f . . 
f c c f a a a a a a a a b b f . 
. f f c a a a a a a a b f f f . 
. . f c a a a a a a b f 1 f f . 
. . f c c a a a a a b f 5 f f . 
. . f c c c a a a a b f f f f . 
. . . f c c c a a a a b f f . . 
. . . . f c c c c c a a b . . . 
. . . . f c c c a a a a f 2 . . 
. . . f c c a a a a a a a f . . 
. . f c c a a a a a a a a a f . 
. . f c a a a a a a a a a a f . 
. f c a a a a a a a a a a a a f 
`;
            case "image4":
            case "MageLeft":return img`
. . . . . . f f f f f f f . . . 
. . . . f f a a c c c c c f . . 
. . . f a a a a a a c c c f . . 
. . f a a a a a a a a c c c f . 
. f b b a a a a a a a a f c c f 
. f f f b a a a a a a a c f f . 
. f f 1 f b a a a a a a c f . . 
. f f 5 f b a a a a a c c f . . 
. f f f f b a a a a c c c f . . 
. . f f b a a a a c c c f . . . 
. . . b a a c c c c c f . . . . 
. . 5 f a a a a c c c f . . . . 
. . f a a a a a a a c c f . . . 
. f a a a a a a a a a c c f . . 
. f a a a a a a a a a a c f . . 
f a a a a a a a a a a a a c f . 
`;
            case "image5":
            case "myImage":return img`
........ffffffff........
.......f44444444f.......
......f4511111154f......
.....f459999999954f.....
.....f598888888895f.....
....f49885555558894f....
....f98555555555589f....
....f85555555555558f....
....f45545455454554f....
.....f454545545454f.....
.....f4fdff11ffdf4f.....
.....f4fd111111df4f.....
....f444ff1111ff444f....
...f44f4f9ffff1f4f44f...
....ff.f99199999f.ff....
.......f99999991f.......
......f9199991999f......
.....f899991999918f.....
.....f188899998888f.....
....f88881888818818f....
.....ff8888818888ff.....
.......ffffffffff.......
.........fddddf.........
..........f11f..........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f c c c c f f . . . . 
. . . f c c f a a f c c f . . . 
. . f c a a f a a f a a c f . . 
. f c a a a c f f c a a a c f . 
. f c a a a a c c a a a a c f . 
. f c a a a a a a a a a a c f . 
. f c a a a a a a a a a a c f . 
. f c c a a a a a a a a c c f . 
. . f c c a a a a a a c c f . . 
. . . f c c c a a c c c f . . . 
. . . f c c c c c c c c f . . . 
. . f c c a a a a a a c c f . . 
. f c c a a a a a a a a c c f . 
. f c a a a a a a a a a a c f . 
f c a a a a a a a a a a a a c f 
`, img`
. . . f f f f f f f . . . . . . 
. . f c c c c c a a f f . . . . 
. . f c c c a a a a a a f . . . 
. f c c c a a a a a a a a f . . 
f c c f a a a a a a a a b b f . 
. f f c a a a a a a a b f f f . 
. . f c a a a a a a b f 1 f f . 
. . f c c a a a a a b f 5 f f . 
. . f c c c a a a a b f f f f . 
. . . f c c c a a a a b f f . . 
. . . . f c c c c c a a b . . . 
. . . . f c c c a a a a f 2 . . 
. . . f c c a a a a a a a f . . 
. . f c c a a a a a a a a a f . 
. . f c a a a a a a a a a a f . 
. f c a a a a a a a a a a a a f 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f c c c c f f . . . . 
. . . f c c a a a a c c f . . . 
. . f c a a a a a a a a c f . . 
. f c a a a b b b b a a a c f . 
. f c a a b f f f f b a a c f . 
. f c a b f 1 f f 1 f b a c f . 
. f c a b f 5 f f 5 f b a c f . 
. f c a b f f f f f f b a c f . 
. . f c a b f f f f b a c f . . 
. . . f f c b b b b c f f . . . 
. . . f c a a 4 5 a a c f . . . 
. . f c a a a 5 2 a a a c f . . 
. f c a a a a c c a a a a c f . 
. f c a a a a c c a a a a c f . 
f c a a a a a c c a a a a a c f 
`, img`
. . . . . . f f f f f f f . . . 
. . . . f f a a c c c c c f . . 
. . . f a a a a a a c c c f . . 
. . f a a a a a a a a c c c f . 
. f b b a a a a a a a a f c c f 
. f f f b a a a a a a a c f f . 
. f f 1 f b a a a a a a c f . . 
. f f 5 f b a a a a a c c f . . 
. f f f f b a a a a c c c f . . 
. . f f b a a a a c c c f . . . 
. . . b a a c c c c c f . . . . 
. . 5 f a a a a c c c f . . . . 
. . f a a a a a a a c c f . . . 
. f a a a a a a a a a c c f . . 
. f a a a a a a a a a a c f . . 
f a a a a a a a a a a a a c f . 
`];
            case "myAnim0":
            case "anim2":return [img`
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........ffffffff........
.......f55555555f.......
......f5559999999f......
.....f555599999999f.....
.....f555599999999f.....
....f44555555555599f....
....f44555555555559f....
....f44555545454545f....
....f44555545454545f....
.....f4555fffffffff.....
.....f445fddddffdf......
.....f44fdd111111f......
....f444ffd1111ff.......
...f44f4f9fffff.........
....ff.f1999199f........
.......f9999991f........
......f999919999f.......
.....f89199999919f......
.....f88889919998f......
....f8188888888881f.....
.....ff881888881ff......
.......fffffffff........
.........fddddf.........
..........f11f..........
`, img`
........ffffffff........
.......f44444444f.......
......f4511111154f......
.....f459999999954f.....
.....f598888888895f.....
....f49885555558894f....
....f98555555555589f....
....f85555555555558f....
....f45545455454554f....
.....f454545545454f.....
.....f4fdffddffdf4f.....
.....f4fd111111df4f.....
....f444ff1111ff444f....
...f44f4f9ffff1f4f44f...
....ff.f99199999f.ff....
.......f99999991f.......
......f9199991999f......
.....f899991999918f.....
.....f188899998888f.....
....f88881888818818f....
.....ff8888818888ff.....
.......ffffffffff.......
.........fddddf.........
..........f11f..........
`, img`
........ffffffff........
.......f55555555f.......
......f1111119555f......
.....f999999995555f.....
.....f988888889555f.....
....f98855555889544f....
....f85555555558544f....
....f54545454555544f....
....f54545454555544f....
.....fffffffff5554f.....
......fdffddddf544f.....
......f111111ddf44f.....
.......ff1111dff444f....
.........fffff9f4f44f...
........f9919991f.ff....
........f1999999f.......
.......f999919999f......
......f91999999198f.....
......f89991998888f.....
.....f1888888888818f....
......ff188888188ff.....
........fffffffff.......
.........fddddf.........
..........f11f..........
`, img`
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
